#spring:
#  application:
#    name: product-service
#server:
#  port: 19093
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:19090/eureka/

# zipkin 학습 위한 코드
spring:
  application:
    name: product-service
server:
  port: 19093
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0


## config 서버 공부 위해 사용한 설정
#server:
#  port: 0  # 임시 포트, 이후 Config 서버 설정으로 덮어씌움
#
#spring:
#  profiles:
#    active: local
#  application:
#    name: product-service
#  config:
#    import: "configserver:"
#  cloud:
#    config:
#      discovery:
#        enabled: true
#        service-id: config-server
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: refresh
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:19090/eureka/
#
#message: "default message"


